name: Build KoticOS ISO

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm xorriso grub-pc-bin qemu-system-i386 binutils gcc-multilib make

      - name: Build KoticOS ISO
        run: make

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: KoticOS.iso
          path: KoticOS.iso
